# Generated by Django 2.2.10 on 2020-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='部門ID')),
                ('name', models.CharField(max_length=255, verbose_name='部門ID')),
                ('location', models.CharField(max_length=255, verbose_name='場所')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
