# Generated by Django 3.0.6 on 2020-05-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='content',
            field=models.CharField(max_length=20, verbose_name='商品名'),
        ),
    ]
