# Generated by Django 3.0.6 on 2020-05-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20200525_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='単価')),
                ('stock_quantity', models.IntegerField(blank=True, default=0, verbose_name='在庫数')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品リスト',
            },
        ),
    ]
