# Generated by Django 3.0.6 on 2020-05-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='顧客名')),
                ('address', models.CharField(blank=True, default='', max_length=150, verbose_name='住所')),
                ('email', models.EmailField(blank=True, default='', max_length=150, verbose_name='メールアドレス')),
                ('user_id', models.CharField(max_length=10, verbose_name='ユーザID')),
                ('password', models.CharField(max_length=10, verbose_name='パスワード')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客リスト',
            },
        ),
    ]
