# Generated by Django 3.0.6 on 2020-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='カテゴリID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
